DROP TABLE IF EXISTS Customer CASCADE;
CREATE TABLE Customer (
    ID_CUSTOMER VARCHAR(50) PRIMARY KEY
);

DROP TABLE IF EXISTS Groups CASCADE;
CREATE TABLE Groups (
    ID_GROUP VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50)
);

DROP TABLE IF EXISTS Category CASCADE;
CREATE TABLE Category (
    ID_CATEGORY VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50),
    ID_SUPER_CATEGORY VARCHAR(50),
    FOREIGN KEY (ID_SUPER_CATEGORY) REFERENCES Category(ID_CATEGORY)
);

DROP TABLE IF EXISTS Product CASCADE;
CREATE TABLE Product (
    ID_PRODUCT VARCHAR(50) PRIMARY KEY,
    ASIN VARCHAR(50) NOT NULL UNIQUE,
    TITLE VARCHAR(500),
    ID_GROUP VARCHAR(50),
    SALESRANK INT,
    TOTAL INT,
    AVG_RATING FLOAT,
    FOREIGN KEY (ID_GROUP) REFERENCES Groups(ID_GROUP)
);

DROP TABLE IF EXISTS Similar_Products CASCADE;
CREATE TABLE Similar_Products (
    ID_PRODUCT VARCHAR(50),
    ID_SIMILAR_PRODUCT VARCHAR(50),
    RANK INT,
    PRIMARY KEY (ID_PRODUCT, ID_SIMILAR_PRODUCT),
    FOREIGN KEY (ID_PRODUCT) REFERENCES Product(ID_PRODUCT),
    FOREIGN KEY (ID_SIMILAR_PRODUCT) REFERENCES Product(ID_PRODUCT)
);

DROP TABLE IF EXISTS Review CASCADE;
CREATE TABLE Review (
    ID_REVIEW VARCHAR(50) PRIMARY KEY,
    ID_PRODUCT VARCHAR(50),
    ID_CUSTOMER VARCHAR(50),
    DT_REVIEW DATE,
    RATING INT CHECK (RATING IN (1, 2, 3, 4, 5)),
    QTD_VOTES INT,
    QTD_HELPFUL_VOTES INT,
    FOREIGN KEY (ID_PRODUCT) REFERENCES Product(ID_PRODUCT),
    FOREIGN KEY (ID_CUSTOMER) REFERENCES Customer(ID_CUSTOMER)
);