CREATE TABLE Customer (
    ID_CUSTOMER VARCHAR(50) PRIMARY KEY
);

CREATE TABLE Group (
    ID_GROUP VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE Category (
    ID_CATEGORY VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50),
    ID_SUPER_CATEGORY VARCHAR(50),
    FOREIGN KEY (ID_SUPER_CATEGORY) REFERENCES Category(ID_CATEGORY)
);

CREATE TABLE Product (
    ID_PRODUCT VARCHAR(50) PRIMARY KEY,
    ASIN VARCHAR(50),
    TITLE VARCHAR(50),
    ID_GROUP VARCHAR(50),
    SALESRANK INT,
    ID_CATEGORY VARCHAR(50),
    FOREIGN KEY (ID_GROUP) REFERENCES Group(ID_GROUP),
    FOREIGN KEY (ID_CATEGORY) REFERENCES Category(ID_CATEGORY)
);

CREATE TABLE Similar_Products (
    ID_SIMILAR_PRODUCT VARCHAR(50) PRIMARY KEY,
    ID_PRODUCT VARCHAR(50),
    ID_SIMILAR_PRODUCT VARCHAR(50),
    RANK INT,
    FOREIGN KEY (ID_PRODUCT) REFERENCES Product(ID_PRODUCT),
    FOREIGN KEY (ID_SIMILAR_PRODUCT) REFERENCES Product(ID_PRODUCT)
);

CREATE TABLE Review (
    ID_REVIEW VARCHAR(50) PRIMARY KEY,
    ID_PRODUCT VARCHAR(50),
    ID_CUSTOMER VARCHAR(50),
    DT_REVIEW DATETIME,
    RATING INT CHECK (RATING IN (1, 2, 3, 4, 5)),
    QTD_VOTES INT,
    QTD_HELPFUL_VOTES INT,
    FOREIGN KEY (ID_PRODUCT) REFERENCES Product(ID_PRODUCT),
    FOREIGN KEY (ID_CUSTOMER) REFERENCES Customer(ID_CUSTOMER)
);